# mash-up of matrix and pipenv examples from <https://github.com/actions/setup-python#usage>
name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # prevent one broken version from stopping all other runs
      matrix:
        # these will be out of date again eventually, add the latest versions
        # and remove the unsupported ones
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Install pipenv
      run: pipx install pipenv
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
        cache: 'pipenv'
    - name: Install dependencies
      run: pipenv install --dev
    - name: Lint with flake8
      run: pipenv run flake8 *.py
      continue-on-error: true
    - name: Typecheck with mypy
      run: pipenv run mypy *.py
    - name: Test with unittest
      run: pipenv run python -m unittest discover -v
    - name: Install as package with pip
      run: pip install .
    - name: Run installed version
      run: |
        focstest --version
